<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Attendance Sheet - {{ $announcement->title }}</title>
    <style>
        @page { margin: 28px 32px; }
        body { color: #111; font-family: DejaVu Serif, serif; font-size: 10px; }
        .header { line-height: 1.25; text-align: center; }
        .header .republic { font-size: 10px; }
        .header .office { font-size: 9px; }
        h1 { font-size: 14px; letter-spacing: .3px; margin: 6px 0 28px; }
        .meta { border-collapse: collapse; margin: 0 0 12px; width: 58%; }
        .meta td { padding: 3px 0; vertical-align: bottom; }
        .meta .label { white-space: nowrap; width: 72px; }
        .meta .line { border-bottom: 1px solid #222; padding: 3px 8px 2px; }
        .meta .time-label { padding-left: 12px; width: 48px; }
        table.data { border-collapse: collapse; table-layout: fixed; width: 100%; }
        .data th { font-size: 9px; height: 22px; padding: 3px 5px; text-align: center; }
        .data td { border: 1px solid #222; height: 21px; padding: 3px 5px; }
        .data tr { page-break-inside: avoid; }
        .number { text-align: center; width: 7%; }
        .name { width: 35%; }
        .zone { width: 15%; }
        .check-in { width: 16%; }
        .signature { width: 27%; }
        .prepared { margin-top: 28px; line-height: 1.5; }
        .footer { color: #52605a; font-family: DejaVu Sans, sans-serif; font-size: 8px; margin-top: 25px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div class="republic">REPUBLIC OF THE PHILIPPINES</div>
        <div class="office">PROVINCE OF CAMARINES SUR · MUNICIPALITY/CITY OF IRIGA CITY · BARANGAY SAN JOSE</div>
        <h1>ATTENDANCE SHEET</h1>
    </div>
    <table class="meta">
        <tr>
            <td class="label">Activity/Event:</td>
            <td class="line">{{ $announcement->title }}</td>
        </tr>
        <tr>
            <td class="label">Date:</td>
            <td class="line">{{ $announcement->event_start_at?->format('F j, Y') ?? ' ' }}</td>
            <td class="time-label">Time:</td>
            <td class="line">{{ $announcement->event_start_at?->format('g:i A') ?? ' ' }}</td>
        </tr>
        <tr>
            <td class="label">Venue:</td>
            <td class="line" colspan="3">{{ $announcement->venue_name ?: ' ' }}</td>
        </tr>
    </table>

    <table class="data">
        <thead><tr><th class="number">NO.</th><th class="name">NAME</th><th class="zone">ZONE</th><th class="check-in">CHECK IN</th><th class="signature">SIGNATURE</th></tr></thead>
        <tbody>
        @for ($index = 0; $index < max(10, $attendees->count()); $index++)
            @php($attendance = $attendees->get($index))
            <tr>
                <td class="number">{{ $index + 1 }}</td>
                <td>{{ $attendance?->user?->full_name }}</td>
                <td>{{ $attendance?->user?->zone ? 'Zone ' . $attendance->user->zone : '' }}</td>
                <td>{{ $attendance?->scanned_at?->format('g:i A') }}</td>
                <td></td>
            </tr>
        @endfor
        </tbody>
    </table>
    @php($preparer = auth()->user())
    <div class="prepared">
        <div>Prepared by:</div>
        <div><strong>{{ $preparer?->full_name ?? ' ' }}</strong></div>
        <div>Position: {{ $preparer?->official_position ?? 'Kagawad' }}</div>
        <div>Date: {{ now()->format('F j, Y') }}</div>
    </div>
    <div class="footer">Generated by TalaFair · {{ now()->format('F j, Y, g:i A') }}</div>
</body>
</html>
